name: Run apidiff

on: [ pull_request ]

permissions:
  contents: read

jobs:
  apidiff:
    runs-on: ubuntu-latest
    if: github.base_ref
    steps:
      - name: Install Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: 1.18.x
      - name: Add GOBIN to PATH
        run: echo "PATH=$(go env GOPATH)/bin:$PATH" >>$GITHUB_ENV
      - name: Install dependencies
        run: GO111MODULE=off go get golang.org/x/exp/cmd/apidiff
      - name: Checkout old code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.5.3
        with:
          ref: ${{ github.base_ref }}
          path: "old"
      - name: Checkout new code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.5.3
        with:
          path: "new"
      - name: APIDiff
        run: ./_tools/apidiff.sh -d ../old
        working-directory: "new"
