name: Run tests

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        version: [ '1.15', '1.16', '1.17', '1.18' ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: ${{ matrix.version }}
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.5.3
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v -race ./...
